# compilers
CC_UNIX = cc
CC_WINE = winegcc

# debuggers
DEBUGGER_UNIX = gdb
DEBUGGER_WINE = winedbg

# compiler flags
CFLAGS         = -Wall -Werror -Wpedantic -I$(INCLUDE_DIR) -D_POSIX_C_SOURCE=199309L #TODO: remove this feature test macro
CFLAGS_UNIX    = -ansi -DENABLE_BACKEND_X11
CFLAGS_WINE    = -std=c99 -DENABLE_BACKEND_WINDOWS
CFLAGS_RELEASE = -Og -g -DDEBUG
CFLAGS_DEBUG   = -O3

# library dependencies
LIBS_UNIX = x11
LIBS_WINE = 

# linker flags
LDFLAGS_UNIX = $(shell pkg-config --cflags --libs $(LIBS_UNIX))
LDFLAGS_WINE = $(shell pkg-config --cflags --libs $(LIBS_WINE))

# subdirectories
SUBDIR_BACKEND_X11     = backends/x11
SUBDIR_BACKEND_WINDOWS = backends/windows
SUBDIR_DEMO            = demo

# target platforms
SUBDIR_UNIX = unix
SUBDIR_WINE = wine

# build profiles
SUBDIR_RELEASE = release
SUBDIR_DEBUG   = debug

# public-facing include directory
INCLUDE_DIR = include

# public-facing include files
INCLUDES = $(wildcard $(INCLUDE_DIR)/*.h)

# source file directories
SOURCE_DIR                 = src
SOURCE_DIR_BACKEND_X11     = $(SOURCE_DIR)/$(SUBDIR_BACKEND_X11)
SOURCE_DIR_BACKEND_WINDOWS = $(SOURCE_DIR)/$(SUBDIR_BACKEND_WINDOWS)
SOURCE_DIR_DEMO            = $(SUBDIR_DEMO)

# source files
SOURCES                 = $(wildcard $(SOURCE_DIR)/*.c)
SOURCES_BACKEND_X11     = $(wildcard $(SOURCE_DIR_BACKEND_X11)/*.c)
SOURCES_BACKEND_WINDOWS = $(wildcard $(SOURCE_DIR_BACKEND_WINDOWS)/*.c)
SOURCES_DEMO            = $(wildcard $(SOURCE_DIR_DEMO)/*.c)

# build directories
BUILD_DIR              = build
BUILD_DIR_UNIX         = $(BUILD_DIR)/$(SUBDIR_UNIX)
BUILD_DIR_WINE         = $(BUILD_DIR)/$(SUBDIR_WINE)
BUILD_DIR_UNIX_RELEASE = $(BUILD_DIR_UNIX)/$(SUBDIR_RELEASE)
BUILD_DIR_UNIX_DEBUG   = $(BUILD_DIR_UNIX)/$(SUBDIR_DEBUG)
BUILD_DIR_WINE_RELEASE = $(BUILD_DIR_WINE)/$(SUBDIR_RELEASE)
BUILD_DIR_WINE_DEBUG   = $(BUILD_DIR_WINE)/$(SUBDIR_DEBUG)

# build targets
TARGET_STATIC              = libgosh.a
TARGET_SHARED              = libgosh.so
TARGET_DEMO                = gosh_demo
TARGET_WINE_SUFFIX         = .exe
TARGET_UNIX_RELEASE_STATIC = $(BUILD_DIR_UNIX_RELEASE)/$(TARGET_STATIC)
TARGET_UNIX_RELEASE_SHARED = $(BUILD_DIR_UNIX_RELEASE)/$(TARGET_SHARED)
TARGET_UNIX_RELEASE_DEMO   = $(BUILD_DIR_UNIX_RELEASE)/$(TARGET_DEMO)
TARGET_UNIX_DEBUG_STATIC   = $(BUILD_DIR_UNIX_DEBUG)/$(TARGET_STATIC)
TARGET_UNIX_DEBUG_SHARED   = $(BUILD_DIR_UNIX_DEBUG)/$(TARGET_SHARED)
TARGET_UNIX_DEBUG_DEMO     = $(BUILD_DIR_UNIX_DEBUG)/$(TARGET_DEMO)
TARGET_WINE_RELEASE_STATIC = $(BUILD_DIR_WINE_RELEASE)/$(TARGET_STATIC)
TARGET_WINE_RELEASE_SHARED = $(BUILD_DIR_WINE_RELEASE)/$(TARGET_SHARED)
TARGET_WINE_RELEASE_DEMO   = $(BUILD_DIR_WINE_RELEASE)/$(TARGET_DEMO)$(TARGET_WINE_SUFFIX)
TARGET_WINE_DEBUG_STATIC   = $(BUILD_DIR_WINE_DEBUG)/$(TARGET_STATIC)
TARGET_WINE_DEBUG_SHARED   = $(BUILD_DIR_WINE_DEBUG)/$(TARGET_SHARED)
TARGET_WINE_DEBUG_DEMO     = $(BUILD_DIR_WINE_DEBUG)/$(TARGET_DEMO)$(TARGET_WINE_SUFFIX)

# object file directories
OBJECT_DIR                              = obj
OBJECT_DIR_UNIX                         = $(OBJECT_DIR)/$(SUBDIR_UNIX)
OBJECT_DIR_UNIX_RELEASE                 = $(OBJECT_DIR_UNIX)/$(SUBDIR_RELEASE)
OBJECT_DIR_UNIX_RELEASE_BACKEND_X11     = $(OBJECT_DIR_UNIX_RELEASE)/$(SUBDIR_BACKEND_X11)
OBJECT_DIR_UNIX_RELEASE_BACKEND_WINDOWS = $(OBJECT_DIR_UNIX_RELEASE)/$(SUBDIR_BACKEND_WINDOWS)
OBJECT_DIR_UNIX_RELEASE_DEMO            = $(OBJECT_DIR_UNIX_RELEASE)/$(SUBDIR_DEMO)
OBJECT_DIR_UNIX_DEBUG                   = $(OBJECT_DIR_UNIX)/$(SUBDIR_DEBUG)
OBJECT_DIR_UNIX_DEBUG_BACKEND_X11       = $(OBJECT_DIR_UNIX_DEBUG)/$(SUBDIR_BACKEND_X11)
OBJECT_DIR_UNIX_DEBUG_BACKEND_WINDOWS   = $(OBJECT_DIR_UNIX_DEBUG)/$(SUBDIR_BACKEND_WINDOWS)
OBJECT_DIR_UNIX_DEBUG_DEMO              = $(OBJECT_DIR_UNIX_DEBUG)/$(SUBDIR_DEMO)
OBJECT_DIR_WINE                         = $(OBJECT_DIR)/$(SUBDIR_WINE)
OBJECT_DIR_WINE_RELEASE                 = $(OBJECT_DIR_WINE)/$(SUBDIR_RELEASE)
OBJECT_DIR_WINE_RELEASE_BACKEND_X11     = $(OBJECT_DIR_WINE_RELEASE)/$(SUBDIR_BACKEND_X11)
OBJECT_DIR_WINE_RELEASE_BACKEND_WINDOWS = $(OBJECT_DIR_WINE_RELEASE)/$(SUBDIR_BACKEND_WINDOWS)
OBJECT_DIR_WINE_RELEASE_DEMO            = $(OBJECT_DIR_WINE_RELEASE)/$(SUBDIR_DEMO)
OBJECT_DIR_WINE_DEBUG                   = $(OBJECT_DIR_WINE)/$(SUBDIR_DEBUG)
OBJECT_DIR_WINE_DEBUG_BACKEND_X11       = $(OBJECT_DIR_WINE_DEBUG)/$(SUBDIR_BACKEND_X11)
OBJECT_DIR_WINE_DEBUG_BACKEND_WINDOWS   = $(OBJECT_DIR_WINE_DEBUG)/$(SUBDIR_BACKEND_WINDOWS)
OBJECT_DIR_WINE_DEBUG_DEMO              = $(OBJECT_DIR_WINE_DEBUG)/$(SUBDIR_DEMO)

# intermediate directory stamps
DIR_STAMP_SUFFIX = .dirstamp
OBJECT_DIR_STAMP                              = $(OBJECT_DIR_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_STAMP                         = $(OBJECT_DIR_UNIX_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_RELEASE_STAMP                 = $(OBJECT_DIR_UNIX_RELEASE_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_RELEASE_BACKEND_X11_STAMP     = $(OBJECT_DIR_UNIX_RELEASE_BACKEND_X11_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_RELEASE_BACKEND_WINDOWS_STAMP = $(OBJECT_DIR_UNIX_RELEASE_BACKEND_WINDOWS_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_RELEASE_DEMO_STAMP            = $(OBJECT_DIR_UNIX_RELEASE_DEMO_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_DEBUG_STAMP                   = $(OBJECT_DIR_UNIX_DEBUG_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_DEBUG_BACKEND_X11_STAMP       = $(OBJECT_DIR_UNIX_DEBUG_BACKEND_X11_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_DEBUG_BACKEND_WINDOWS_STAMP   = $(OBJECT_DIR_UNIX_DEBUG_BACKEND_WINDOWS_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_UNIX_DEBUG_DEMO_STAMP              = $(OBJECT_DIR_UNIX_DEBUG_DEMO_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_STAMP                         = $(OBJECT_DIR_WINE_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_RELEASE_STAMP                 = $(OBJECT_DIR_WINE_RELEASE_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_RELEASE_BACKEND_X11_STAMP     = $(OBJECT_DIR_WINE_RELEASE_BACKEND_X11_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_RELEASE_BACKEND_WINDOWS_STAMP = $(OBJECT_DIR_WINE_RELEASE_BACKEND_WINDOWS_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_RELEASE_DEMO_STAMP            = $(OBJECT_DIR_WINE_RELEASE_DEMO_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_DEBUG_STAMP                   = $(OBJECT_DIR_WINE_DEBUG_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_DEBUG_BACKEND_X11_STAMP       = $(OBJECT_DIR_WINE_DEBUG_BACKEND_X11_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_DEBUG_BACKEND_WINDOWS_STAMP   = $(OBJECT_DIR_WINE_DEBUG_BACKEND_WINDOWS_STAMP)/$(DIR_STAMP_SUFFIX)
OBJECT_DIR_WINE_DEBUG_DEMO_STAMP              = $(OBJECT_DIR_WINE_DEBUG_DEMO_STAMP)/$(DIR_STAMP_SUFFIX)

# object files
STATIC_SUFFIX = _static
SHARED_SUFFIX = _shared
OBJECTS_UNIX_RELEASE_STATIC                 = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_UNIX_RELEASE)/%$(STATIC_SUFFIX).o,$(SOURCES))
OBJECTS_UNIX_RELEASE_SHARED                 = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_UNIX_RELEASE)/%$(SHARED_SUFFIX).o,$(SOURCES))
OBJECTS_UNIX_RELEASE_BACKEND_X11_STATIC     = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_UNIX_RELEASE_BACKEND_X11)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_UNIX_RELEASE_BACKEND_X11_SHARED     = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_UNIX_RELEASE_BACKEND_X11)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_UNIX_RELEASE_BACKEND_WINDOWS_STATIC = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_UNIX_RELEASE_BACKEND_WINDOWS)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_UNIX_RELEASE_BACKEND_WINDOWS_SHARED = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_UNIX_RELEASE_BACKEND_WINDOWS)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_UNIX_RELEASE_DEMO                   = $(patsubst $(SOURCE_DIR_DEMO)/%.c,$(OBJECT_DIR_UNIX_RELEASE)/%$(SHARED_SUFFIX).o,$(SOURCES_DEMO))
OBJECTS_UNIX_DEBUG_STATIC                   = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_UNIX_DEBUG)/%$(STATIC_SUFFIX).o,$(SOURCES))
OBJECTS_UNIX_DEBUG_SHARED                   = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_UNIX_DEBUG)/%$(SHARED_SUFFIX).o,$(SOURCES))
OBJECTS_UNIX_DEBUG_BACKEND_X11_STATIC       = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_UNIX_DEBUG_BACKEND_X11)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_UNIX_DEBUG_BACKEND_X11_SHARED       = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_UNIX_DEBUG_BACKEND_X11)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_UNIX_DEBUG_BACKEND_WINDOWS_STATIC   = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_UNIX_DEBUG_BACKEND_WINDOWS)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_UNIX_DEBUG_BACKEND_WINDOWS_SHARED   = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_UNIX_DEBUG_BACKEND_WINDOWS)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_UNIX_DEBUG_DEMO                     = $(patsubst $(SOURCE_DIR_DEMO)/%.c,$(OBJECT_DIR_UNIX_DEBUG)/%$(SHARED_SUFFIX).o,$(SOURCES_DEMO))
OBJECTS_WINE_RELEASE_STATIC                 = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_WINE_RELEASE)/%$(STATIC_SUFFIX).o,$(SOURCES))
OBJECTS_WINE_RELEASE_SHARED                 = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_WINE_RELEASE)/%$(SHARED_SUFFIX).o,$(SOURCES))
OBJECTS_WINE_RELEASE_BACKEND_X11_STATIC     = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_WINE_RELEASE_BACKEND_X11)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_WINE_RELEASE_BACKEND_X11_SHARED     = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_WINE_RELEASE_BACKEND_X11)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_WINE_RELEASE_BACKEND_WINDOWS_STATIC = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_WINE_RELEASE_BACKEND_WINDOWS)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_WINE_RELEASE_BACKEND_WINDOWS_SHARED = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_WINE_RELEASE_BACKEND_WINDOWS)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_WINE_RELEASE_DEMO                   = $(patsubst $(SOURCE_DIR_DEMO)/%.c,$(OBJECT_DIR_WINE_RELEASE)/%$(SHARED_SUFFIX).o,$(SOURCES_DEMO))
OBJECTS_WINE_DEBUG_STATIC                   = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_WINE_DEBUG)/%$(STATIC_SUFFIX).o,$(SOURCES))
OBJECTS_WINE_DEBUG_SHARED                   = $(patsubst $(SOURCE_DIR)/%.c,$(OBJECT_DIR_WINE_DEBUG)/%$(SHARED_SUFFIX).o,$(SOURCES))
OBJECTS_WINE_DEBUG_BACKEND_X11_STATIC       = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_WINE_DEBUG_BACKEND_X11)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_WINE_DEBUG_BACKEND_X11_SHARED       = $(patsubst $(SOURCE_DIR_BACKEND_X11)/%.c,$(OBJECT_DIR_WINE_DEBUG_BACKEND_X11)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_X11))
OBJECTS_WINE_DEBUG_BACKEND_WINDOWS_STATIC   = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_WINE_DEBUG_BACKEND_WINDOWS)/%$(STATIC_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_WINE_DEBUG_BACKEND_WINDOWS_SHARED   = $(patsubst $(SOURCE_DIR_BACKEND_WINDOWS)/%.c,$(OBJECT_DIR_WINE_DEBUG_BACKEND_WINDOWS)/%$(SHARED_SUFFIX).o,$(SOURCES_BACKEND_WINDOWS))
OBJECTS_WINE_DEBUG_DEMO                     = $(patsubst $(SOURCE_DIR_DEMO)/%.c,$(OBJECT_DIR_WINE_DEBUG)/%$(SHARED_SUFFIX).o,$(SOURCES_DEMO))

# dependency files
DEPENDENCIES_UNIX_RELEASE_STATIC                 = $(OBJECTS_UNIX_RELEASE_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_SHARED                 = $(OBJECTS_UNIX_RELEASE_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_BACKEND_X11_STATIC     = $(OBJECTS_UNIX_RELEASE_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_BACKEND_X11_SHARED     = $(OBJECTS_UNIX_RELEASE_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_BACKEND_WINDOWS_STATIC = $(OBJECTS_UNIX_RELEASE_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_BACKEND_WINDOWS_SHARED = $(OBJECTS_UNIX_RELEASE_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_RELEASE_DEMO                   = $(OBJECTS_UNIX_RELEASE_DEMO:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_STATIC                   = $(OBJECTS_UNIX_DEBUG_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_SHARED                   = $(OBJECTS_UNIX_DEBUG_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_BACKEND_X11_STATIC       = $(OBJECTS_UNIX_DEBUG_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_BACKEND_X11_SHARED       = $(OBJECTS_UNIX_DEBUG_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_BACKEND_WINDOWS_STATIC   = $(OBJECTS_UNIX_DEBUG_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_BACKEND_WINDOWS_SHARED   = $(OBJECTS_UNIX_DEBUG_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_UNIX_DEBUG_DEMO                     = $(OBJECTS_UNIX_DEBUG_DEMO:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_STATIC                 = $(OBJECTS_WINE_RELEASE_STATIC:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_SHARED                 = $(OBJECTS_WINE_RELEASE_SHARED:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_BACKEND_X11_STATIC     = $(OBJECTS_WINE_RELEASE_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_BACKEND_X11_SHARED     = $(OBJECTS_WINE_RELEASE_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_BACKEND_WINDOWS_STATIC = $(OBJECTS_WINE_RELEASE_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_BACKEND_WINDOWS_SHARED = $(OBJECTS_WINE_RELEASE_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_WINE_RELEASE_DEMO                   = $(OBJECTS_WINE_RELEASE_DEMO:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_STATIC                   = $(OBJECTS_WINE_DEBUG_STATIC:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_SHARED                   = $(OBJECTS_WINE_DEBUG_SHARED:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_BACKEND_X11_STATIC       = $(OBJECTS_WINE_DEBUG_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_BACKEND_X11_SHARED       = $(OBJECTS_WINE_DEBUG_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_BACKEND_WINDOWS_STATIC   = $(OBJECTS_WINE_DEBUG_BACKEND_X11_STATIC:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_BACKEND_WINDOWS_SHARED   = $(OBJECTS_WINE_DEBUG_BACKEND_X11_SHARED:%.o=%.d)
DEPENDENCIES_WINE_DEBUG_DEMO                     = $(OBJECTS_WINE_DEBUG_DEMO:%.o=%.d)

-include $(DEPENDENCIES_UNIX_RELEASE_STATIC)
-include $(DEPENDENCIES_UNIX_RELEASE_SHARED)
-include $(DEPENDENCIES_UNIX_RELEASE_BACKEND_X11_STATIC)
-include $(DEPENDENCIES_UNIX_RELEASE_BACKEND_X11_SHARED)
-include $(DEPENDENCIES_UNIX_RELEASE_BACKEND_WINDOWS_STATIC)
-include $(DEPENDENCIES_UNIX_RELEASE_BACKEND_WINDOWS_SHARED)
-include $(DEPENDENCIES_UNIX_RELEASE_DEMO)
-include $(DEPENDENCIES_UNIX_DEBUG_STATIC)
-include $(DEPENDENCIES_UNIX_DEBUG_SHARED)
-include $(DEPENDENCIES_UNIX_DEBUG_BACKEND_X11_STATIC)
-include $(DEPENDENCIES_UNIX_DEBUG_BACKEND_X11_SHARED)
-include $(DEPENDENCIES_UNIX_DEBUG_BACKEND_WINDOWS_STATIC)
-include $(DEPENDENCIES_UNIX_DEBUG_BACKEND_WINDOWS_SHARED)
-include $(DEPENDENCIES_UNIX_DEBUG_DEMO)
-include $(DEPENDENCIES_RELEASE_RELEASE_STATIC)
-include $(DEPENDENCIES_RELEASE_RELEASE_SHARED)
-include $(DEPENDENCIES_RELEASE_RELEASE_BACKEND_X11_STATIC)
-include $(DEPENDENCIES_RELEASE_RELEASE_BACKEND_X11_SHARED)
-include $(DEPENDENCIES_RELEASE_RELEASE_BACKEND_WINDOWS_STATIC)
-include $(DEPENDENCIES_RELEASE_RELEASE_BACKEND_WINDOWS_SHARED)
-include $(DEPENDENCIES_RELEASE_RELEASE_DEMO)
-include $(DEPENDENCIES_RELEASE_DEBUG_STATIC)
-include $(DEPENDENCIES_RELEASE_DEBUG_SHARED)
-include $(DEPENDENCIES_RELEASE_DEBUG_BACKEND_X11_STATIC)
-include $(DEPENDENCIES_RELEASE_DEBUG_BACKEND_X11_SHARED)
-include $(DEPENDENCIES_RELEASE_DEBUG_BACKEND_WINDOWS_STATIC)
-include $(DEPENDENCIES_RELEASE_DEBUG_BACKEND_WINDOWS_SHARED)
-include $(DEPENDENCIES_RELEASE_DEBUG_DEMO)

ifeq ($(PREFIX),)
    PREFIX = /usr
endif
INSTALL_PREFIX = $(DESTDIR)$(PREFIX)

.PHONY: all
all: unixrelease

.PHONY: unixrelease
unixrelease: CFLAGS  += $(CFLAGS_UNUX) $(CFLAGS_RELEASE)
unixrelease: LDFLAGS += $(LDFLAGS_UNIX)
unixrelease: $(TARGET_UNIX_RELEASE_DEMO) $(TARGET_UNIX_RELEASE_STATIC) $(TARGET_UNIX_RELEASE_SHARED)

.PHONY: unixdebug
unixdebug: CFLAGS  += $(CFLAGS_UNUX) $(CFLAGS_DEBUG)
unixdebug: LDFLAGS += $(LDFLAGS_UNIX)
unixdebug: $(TARGET_UNIX_DEBUG_DEMO)
	$(DEBUGGER_UNIX) -ex run --arg $<

.PHONY: winerelease
winerelease: CFLAGS  += $(CFLAGS_WINE) $(CFLAGS_RELEASE)
winerelease: LDFLAGS += $(LDFLAGS_UNIX)
unixrelease: $(TARGET_WINE_RELEASE_DEMO) $(TARGET_WINE_RELEASE_STATIC) $(TARGET_WINE_RELEASE_SHARED)

.PHONY: winedebug
winedebug: CFLAGS  += $(CFLAGS_WINE) $(CFLAGS_DEBUG)
winedebug: LDFLAGS += $(LDFLAGS_WINE)
winedebug: $(TARGET_WINE_DEBUG_DEMO)
	$(DEBUGGER_WINE) --gdb $<

$(TARGET_UNIX_RELEASE_DEMO): $(OBJECTS_UNIX_RELEASE_STATIC) $(OBJECTS_UNIX_RELEASE

%.a: $(BUILD_DIR_STAMP) $(OBJECTS_STATIC)
	ar rcs $@ $(filter-out $<,$^)

%.so: $(BUILD_DIR_STAMP) $(OBJECTS_SHARED)
	$(CC) $(CFLAGS) -shared -o $@ $(filter-out $<,$^) $(LDFLAGS)

$(TARGET_DEMO): $(BUILD_DIR_STAMP) $(OBJECTS_STATIC) $(OBJECTS_DEMO)
	$(CC) $(CFLAGS) -o $@ $(filter-out $<,$^) $(LDFLAGS)

$(OBJECTS_STATIC): $(OBJECT_DIR)/%_static.o: $(SOURCE_DIR)/%.c $(OBJECT_DIR_STAMP) $(DEPENDENCIES)
	$(CC) $(CFLAGS) -MMD -c -o $@ $<

$(OBJECTS_SHARED): $(OBJECT_DIR)/%_shared.o: $(SOURCE_DIR)/%.c $(OBJECT_DIR_STAMP) $(DEPENDENCIES)
	$(CC) $(CFLAGS) -MMD -fPIC -c -o $@ $<

$(OBJECTS_DEMO): $(DEMO_OBJECT_DIR)/%.o: $(DEMO_SOURCE_DIR)/%.c $(DEMO_OBJECT_DIR_STAMP) $(DEPENDENCIES)
	$(CC) $(CFLAGS) -MMD -c -o $@ $<

.PRECIOUS: %/.dirstamp
%/.dirstamp:
	mkdir -p $(@D)
	touch $@

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR) $(OBJECT_DIR)

.PHONY: install
install: unixrelease
	install -d $(INSTALL_PREFIX)/include
	install -d $(INSTALL_PREFIX)/lib
	install -d $(INSTALL_PREFIX)/bin
	install -m 644 $(INCLUDES) $(INSTALL_PREFIX)/include
	install -m 644 $(TARGET_STATIC) $(TARGET_SHARED) $(INSTALL_PREFIX)/lib
	install -m 644 $(TARGET_DEMO) $(INSTALL_PREFIX)/bin
